required = [
    "github.com/lightstep/lightstep-tracer-common/golang/protobuf/lightsteppb",
    "github.com/lightstep/lightstep-tracer-common/golang/protobuf/collectorpb",
    "github.com/lightstep/lightstep-tracer-common/golang/protobuf/collectorpb/collectorpbfakes",
]

[[constraint]]
  name = "github.com/lightstep/lightstep-tracer-common"
  revision = "5c08c8156e1a492c2938fcf2cc6375921ad14abc"
  # ^^^ TODO This will be commited as
  #  version = "1.0.2"
  # before this PR merges.

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.0.0"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.4.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.2.0"

[[constraint]]
  name = "github.com/opentracing/opentracing-go"
  version = "1.0.2"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.4.3"
