required = [
    "github.com/lightstep/lightstep-tracer-common/golang/protobuf/lightsteppb",
    "github.com/lightstep/lightstep-tracer-common/golang/protobuf/collectorpb",
    "github.com/lightstep/lightstep-tracer-common/golang/protobuf/collectorpb/collectorpbfakes",
]

[[constraint]]
  name = "github.com/lightstep/lightstep-tracer-common"
  revision = "e0f5cbb64acde8692705c310aebe5c8bb1d13df4"
  # ^^^ This will become
  #  version = "1.0.3"
  # after that version pins protobuf version != master.

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.0.0"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.4.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.2.0"

[[constraint]]
  name = "github.com/opentracing/opentracing-go"
  version = "1.0.2"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.4.3"
